#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Wed May 19 12:52:21 2021
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from MyFrame import MyFrame


class MyApp(wx.App):
    def OnInit(self):
        self.foframe = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.foframe)
        self.foframe.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
