#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Wed May 19 13:01:44 2021
#

import wx
from feladat import foglalasok
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class FoglalasFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle(u"Foglalások")
        self.Hide()

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Foglalások")
        sizer_2.Add(label_1, 1, wx.ALL, 6)

        self.list_box_1 = wx.ListBox(self.panel_1, wx.ID_ANY, choices=[str(foglalas) for foglalas in foglalasok])
        sizer_2.Add(self.list_box_1, 3, wx.ALL | wx.EXPAND, 6)

        self.button_vissza_fo = wx.Button(self.panel_1, wx.ID_ANY, "Vissza")
        sizer_2.Add(self.button_vissza_fo, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 6)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.click_vissza_fo, self.button_vissza_fo)
        # end wxGlade

    def click_vissza_fo(self, event):  # wxGlade: MyFrame.<event_handler>
        self.Hide()
        event.Skip()

# end of class MyFrame
