#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Wed May 19 12:58:33 2021
#

import wx
import feladat
from vendeg import Vendeg
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class VendegFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle(u"Új vendég felvétele")
        self.Hide()
        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Új vendég neve:")
        sizer_3.Add(label_1, 0, 0, 0)

        self.text_ctrl_ujVendeg = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_3.Add(self.text_ctrl_ujVendeg, 1, wx.ALL | wx.EXPAND, 6)

        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, u"Új vendég személyi száma")
        sizer_4.Add(label_2, 0, 0, 0)

        self.text_ctrl_ujSzemelyi = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_4.Add(self.text_ctrl_ujSzemelyi, 1, wx.ALL | wx.EXPAND, 6)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_5, 1, wx.EXPAND, 0)

        self.button_felveszVendeg = wx.Button(self.panel_1, wx.ID_ANY, "Felvesz")
        sizer_5.Add(self.button_felveszVendeg, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 10)

        self.button_2 = wx.Button(self.panel_1, wx.ID_ANY, "Vissza")
        sizer_5.Add(self.button_2, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 10)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.click_felveszVendeg, self.button_felveszVendeg)
        self.Bind(wx.EVT_BUTTON, self.click_vissza, self.button_2)
        # end wxGlade
        
    def click_felveszVendeg(self, event):  # wxGlade: MyFrame.<event_handler>
        nev=self.text_ctrl_ujVendeg.GetValue().split()
        
        szam=self.text_ctrl_ujSzemelyi.GetValue()
        if nev!="" and szam!="":
            with open(feladat.FAJLV, "a", encoding="utf-8") as f:
                f.write(str(Vendeg(nev[0], nev[1], szam)))
                f.close()
        event.Skip()

    def click_vissza(self, event):  # wxGlade: MyFrame.<event_handler>
        self.foglalasFrame.Hide()
        event.Skip()

# end of class MyFrame
