#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sun May 16 22:16:21 2021
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from fogaszat import MainFrame

# from MyFrame import MyFrame


class MyApp(wx.App):
    def OnInit(self):
        self.frame = MainFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True


# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()


"""self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        ujFoglitem = wxglade_tmp_menu.Append(wx.ID_ANY, "új foglalás felvitele", "")
        self.Bind(wx.EVT_MENU, self.uj_foglalas_listaba, ujFoglitem)
        foglMentitem = wxglade_tmp_menu.Append(wx.ID_ANY, "mentés fájlba", "")
        self.Bind(wx.EVT_MENU, self.menu_foglalas_mentes, foglMentitem)
        self.frame_menubar.Append(wxglade_tmp_menu, "Foglalások")
        wxglade_tmp_menu = wx.Menu()
        ujPaciensitem = wxglade_tmp_menu.Append(wx.ID_ANY, "Új páciens", "")
        self.Bind(wx.EVT_MENU, self.uj_paciens_listaba, ujPaciensitem)
        mentesFajlbaitem = wxglade_tmp_menu.Append(wx.ID_ANY, "mentés fájlba", "")
        self.Bind(wx.EVT_MENU, self.menu_mentes_fajlba, mentesFajlbaitem)
        self.frame_menubar.Append(wxglade_tmp_menu, "Páciensek")
        wxglade_tmp_menu = wx.Menu()
        self.frame_menubar.Append(wxglade_tmp_menu, "Kilépés")
        self.Bind(wx.EVT_MENU, self.menu_kilep, kilepItem)
        self.SetMenuBar(self.frame_menubar)"""