# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sun May 16 22:16:21 2021
#

import wx
import feladat_fog
from os import path, curdir
baseFolder=path.abspath(curdir)
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class FoglalasFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.MAXIMIZE_BOX | wx.MINIMIZE_BOX | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((758, 600))
        self.SetTitle(u"Foglalások")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("C:\\Users\\Szalamandra\\Documents\\szf\\egressy\\python\\wxgladesprogik\\wxglade_env\\grafikusSzoftver\\fogaszat_python\\src\\fajlok\\img\\fog.jpg", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)
        self.Hide()

        self.panel_foglalas = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.list_box_foglalasok = wx.ListBox(self.panel_foglalas, wx.ID_ANY, choices=[])
        sizer_1.Add(self.list_box_foglalasok, 1, wx.ALL | wx.EXPAND, 6)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        self.button_beolvas_foglalas = wx.Button(self.panel_foglalas, wx.ID_ANY, u"beolvasás", style=wx.BU_AUTODRAW | wx.BU_EXACTFIT)
        sizer_2.Add(self.button_beolvas_foglalas, 1, wx.ALIGN_CENTER_VERTICAL | wx.FIXED_MINSIZE | wx.LEFT | wx.RIGHT, 45)

        self.button_1 = wx.Button(self.panel_foglalas, wx.ID_ANY, "vissza", style=wx.BU_AUTODRAW | wx.BU_EXACTFIT)
        sizer_2.Add(self.button_1, 1, wx.ALIGN_CENTER_VERTICAL | wx.LEFT | wx.RIGHT, 45)

        self.panel_foglalas.SetSizer(sizer_1)

        self.Layout()
        
        self.Bind(wx.EVT_BUTTON, self.click_beolvas_foglalas, self.button_beolvas_foglalas)
        self.Bind(wx.EVT_BUTTON, self.click_vissza, self.button_1)
        # end wxGlade


    def click_close(self, event):  # wxGlade: MyFrame.<event_handler>
        self.Destroy()
        event.Skip()

    def click_vissza(self, event):  # wxGlade: MyFrame.<event_handler>
        self.Hide()
        event.Skip()
    def click_beolvas_foglalas(self, event):  # wxGlade: MyFrame.<event_handler>
        lista=[]
        with open(path.join(baseFolder,"src\\fajlok\\mentesek\\foglalasok.txt"),"r", encoding="utf-8") as f:
            for sor in f:
                sor=sor.strip()
                
                #print(sor)
                lista.append(sor)
        #print(str(lista))
        self.list_box_foglalasok.Set(lista)
        event.Skip()

# end of class MyFrame
