#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Tue May 18 10:20:22 2021
#

import wx
from szemely import Szemely
from os import path, curdir
baseFolder = path.abspath(curdir)

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class PaciensFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle(u"Új páciens felvitele")
        self.Hide()

        self.panel_ujPaci = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_ujPaci, wx.ID_ANY, u"Új páciens neve", style=wx.ALIGN_LEFT)
        sizer_2.Add(label_1, 1, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM | wx.LEFT | wx.TOP, 6)

        self.text_ctrl_ujPaci = wx.TextCtrl(self.panel_ujPaci, wx.ID_ANY, "")
        sizer_2.Add(self.text_ctrl_ujPaci, 1, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM | wx.RIGHT | wx.TOP, 6)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_ujPaci, wx.ID_ANY, u"Személyi igazolvány száma", style=wx.ALIGN_LEFT)
        sizer_3.Add(label_2, 1, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM | wx.LEFT | wx.TOP, 6)

        self.text_ctrl_szemelyiSzam = wx.TextCtrl(self.panel_ujPaci, wx.ID_ANY, "")
        sizer_3.Add(self.text_ctrl_szemelyiSzam, 1, wx.ALIGN_CENTER_VERTICAL | wx.BOTTOM | wx.RIGHT | wx.TOP, 6)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)

        self.button_ujPaciBevitel = wx.Button(self.panel_ujPaci, wx.ID_ANY, u"új páciens felvitele")
        sizer_4.Add(self.button_ujPaciBevitel, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 30)

        self.btn_vissza = wx.Button(self.panel_ujPaci, wx.ID_ANY, "vissza")
        sizer_4.Add(self.btn_vissza, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 30)

        self.panel_ujPaci.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.click_ujPaciBevitel, self.button_ujPaciBevitel)
        self.Bind(wx.EVT_BUTTON, self.click_visszaFrame, self.btn_vissza)
        # end wxGlade

    def click_ujPaciBevitel(self, event):  # wxGlade: MyFrame.<event_handler>
        paci=self.text_ctrl_ujPaci.GetValue()
        szam=self.text_ctrl_szemelyiSzam.GetValue()
        if paci!="" and szam!="":
            print(type(paci),paci)
            nevV,nevK=paci.split()
            with open(path.join(baseFolder,"src\\fajlok\\paciensek.txt"), "a", encoding="utf-8")as f:
                #f.write(f"\n{paci} {szam}")
                f.write(str(Szemely(nevV, nevK, szam)))
            f.close()
            wx.MessageBox("Adatait rögzítettük", "info", wx.OK|wx.ICON_INFORMATION)
        else:
            wx.MessageBox("Kérlek adj meg minden adatot!", 'info', wx.OK| wx.ICON_WARNING)    
        event.Skip()

    def click_visszaFrame(self, event):  # wxGlade: MyFrame.<event_handler>
        self.Destroy()
        event.Skip()

# end of class MyFrame

