#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Fri Apr  2 13:15:38 2021
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from views.MyFrameFo import MyFrameFo


class CovidStat(wx.App):
    def OnInit(self):
        self.frame = MyFrameFo(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True


# end of class CovidStat

if __name__ == "__main__":
    CovidStat = CovidStat(0)
    CovidStat.MainLoop()
