#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sun May 16 10:39:12 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((424, 455))
        self.SetTitle("London")

        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, u"Kilépés", "")
        self.Bind(wx.EVT_MENU, self.click_kilepes, item)
        wxglade_tmp_menu.Append(wx.ID_ANY, "meg legyen egy radio", "", wx.ITEM_RADIO)
        wxglade_tmp_menu.Append(wx.ID_ANY, "checkable", "", wx.ITEM_CHECK)
        wxglade_tmp_menu.Append(wx.ID_ANY, "item", "")
        self.frame_menubar.Append(wxglade_tmp_menu, "File")
        wxglade_tmp_menu = wx.Menu()
        self.frame_menubar.Append(wxglade_tmp_menu, "Edit")
        wxglade_tmp_menu = wx.Menu()
        self.frame_menubar.Append(wxglade_tmp_menu, "Help")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end

        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetMinSize((384, 367))
        sizer_1.Add(self.panel_1, 0, 0, 0)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "London")
        label_1.SetFont(wx.Font(15, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_2.Add(label_1, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_3, 1, wx.ALL | wx.EXPAND, 5)

        self.javit_btn = wx.Button(self.panel_1, wx.ID_ANY, u"javít")
        sizer_3.Add(self.javit_btn, 0, wx.LEFT | wx.RIGHT, 45)

        self.nevjegy_btn = wx.Button(self.panel_1, wx.ID_ANY, u"Névjegy", style=wx.BU_AUTODRAW)
        sizer_3.Add(self.nevjegy_btn, 1, wx.LEFT | wx.RIGHT, 45)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_4, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "4.elso helyezettek")
        sizer_4.Add(label_2, 1, wx.BOTTOM | wx.LEFT | wx.TOP, 10)

        self.text_elso_hely = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_4.Add(self.text_elso_hely, 1, wx.BOTTOM | wx.RIGHT | wx.TOP, 10)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_5, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "5.helyezettek")
        sizer_5.Add(label_3, 1, wx.BOTTOM | wx.LEFT | wx.TOP, 10)

        self.text_helyezettek = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_5.Add(self.text_helyezettek, 1, wx.BOTTOM | wx.RIGHT | wx.TOP, 10)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_6, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, u"6. egyéni helyezettek")
        sizer_6.Add(label_4, 1, wx.BOTTOM | wx.LEFT | wx.TOP, 10)

        self.list_text_egyszeri_vers = wx.ListBox(self.panel_1, wx.ID_ANY, choices=["choice 1"])
        sizer_6.Add(self.list_text_egyszeri_vers, 1, wx.BOTTOM | wx.RIGHT | wx.TOP, 10)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_7, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, u"7.sportágak")
        sizer_7.Add(label_5, 1, wx.BOTTOM | wx.LEFT | wx.TOP, 10)

        self.list_text_sportagak = wx.ListBox(self.panel_1, wx.ID_ANY, choices=["choice 1"])
        sizer_7.Add(self.list_text_sportagak, 1, wx.BOTTOM | wx.RIGHT | wx.TOP, 10)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_8, 1, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, u"8.legtöbbet résztvevő")
        sizer_8.Add(label_6, 1, wx.BOTTOM | wx.LEFT | wx.TOP, 10)

        self.text_legtobb = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_8.Add(self.text_legtobb, 1, wx.BOTTOM | wx.RIGHT | wx.TOP, 10)

        self.feladatok_btn = wx.Button(self.panel_1, wx.ID_ANY, "feladatok")
        sizer_2.Add(self.feladatok_btn, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 15)

        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_9, 1, wx.EXPAND, 0)

        self.ir_btn = wx.Button(self.panel_1, wx.ID_ANY, "iras")
        sizer_9.Add(self.ir_btn, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 10)

        self.olvas_btn = wx.Button(self.panel_1, wx.ID_ANY, "olvasas")
        sizer_9.Add(self.olvas_btn, 1, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 10)

        self.olvas_check_list = wx.CheckListBox(self.panel_1, wx.ID_ANY, choices=["choice 1"])
        sizer_2.Add(self.olvas_check_list, 0, 0, 0)

        self.panel_1.SetSizer(sizer_2)

        self.SetSizer(sizer_1)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.click_javit, self.javit_btn)
        self.Bind(wx.EVT_BUTTON, self.click_nevjegy, self.nevjegy_btn)
        self.Bind(wx.EVT_BUTTON, self.click_feladat, self.feladatok_btn)
        # end wxGlade

    def click_kilepes(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'click_kilepes' not implemented!")
        event.Skip()

    def click_javit(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'click_javit' not implemented!")
        event.Skip()

    def click_nevjegy(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'click_nevjegy' not implemented!")
        event.Skip()

    def click_feladat(self, event):  # wxGlade: MyFrame.<event_handler>
        print("Event handler 'click_feladat' not implemented!")
        event.Skip()

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
